[project]
authors = ["yl <2201441955@qq.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "sonic-mojo"

platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

version = "0.1.0"

[tasks]
build-mojo = { cmd = "rattler-build build --recipe recipes/mojo-recipe.yaml -c https://conda.modular.com/max -c conda-forge --skip-existing=all" }
build-rs = { cmd = "rattler-build build --recipe recipes/rs-recipe.yaml -c https://conda.modular.com/max -c conda-forge --skip-existing=all" }

[dependencies]
max = "*"


[feature.dev.dependencies]
rust = "*"
rattler-build = "*"

#
# ref: https://pixi.sh/latest/features/multi_environment/#ambiguous-environment-selection
#
[environments]
#default = ["default"]
dev = ["dev"]

