[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/furnace-dev",
]

description = "Add a short description here"
name = "try-sonic"
# platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
dev = "mojo run src/main.mojo"

[dependencies]
max = "*"

libsonic = "*"
sonic = "*"
